<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>back</name>
   <tag></tag>
   <elementGuidId>8ab2e65d-f6fb-4ef8-90aa-cee4411c497a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.bi.bi-caret-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[1]/preceding::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>6cae2d98-9793-4d5d-8369-2c0cbb7e47e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>8e0e119b-04f3-49d7-b89d-03396058ae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>aa72e910-54e5-4f9f-9d6f-5cfef7f4ebee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>de86c9ed-5b7e-4b24-adb1-fb50d4401b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>2bbd45f3-7b94-48e1-a5f1-6a0dca44137b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-caret-left</value>
      <webElementGuid>01afc1fa-c4eb-4d81-ba5d-0569f4d333e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>b08374d8-9ba2-4b4e-b4d8-60a3e1ec4c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wg_menu-navbar&quot;]/button[1]/svg[@class=&quot;bi bi-caret-left&quot;]</value>
      <webElementGuid>e8047ecc-c84c-4840-ad57-e84d1c06cef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>975c0ad5-13fa-4e3a-89ea-1bf687bc8fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fried Dumpling'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>bc4cf7e2-67ea-42b1-9a29-06c19a3f358b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
