<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Main</name>
   <tag></tag>
   <elementGuidId>c233f17d-22b8-4972-b312-d3a13bd7bdfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49ab5b20-0303-4bf7-ac97-2ed43320a58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>3f52e4fb-ad90-4a13-94b0-19fc31987732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/category/main'</value>
      <webElementGuid>45b0a557-ec15-4767-a18f-51c48bbd1dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Main</value>
      <webElementGuid>b6876a5f-d0aa-4634-8786-3ba9a390d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wg_category&quot;]/div[@class=&quot;wg_category-container&quot;]/button[@id=&quot;category&quot;]</value>
      <webElementGuid>24f372d0-cb6f-47fc-8c37-e360624be711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='category']</value>
      <webElementGuid>87f8beb0-9116-41d5-91b1-66d691f116d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appetizer'])[1]/following::button[1]</value>
      <webElementGuid>74a7cc42-f6fe-4fe2-9f93-3f33bddfe541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::button[2]</value>
      <webElementGuid>5ff1c8c1-51b9-4166-be95-9d7d39dacf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drink'])[1]/preceding::button[1]</value>
      <webElementGuid>627ebd1e-b6c7-47fc-a1b0-3ffcef03047a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Main']/parent::*</value>
      <webElementGuid>0e775df4-a039-4e07-8f41-14d8aff888d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>82e1f8b0-1a37-40e7-876e-5c713f7c0379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'category' and (text() = 'Main' or . = 'Main')]</value>
      <webElementGuid>cc1c69a9-fa84-4cef-bf8c-b1a3116b4fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
