<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appetizer (1)</name>
   <tag></tag>
   <elementGuidId>3493b572-762c-4164-80bf-42ee59674616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appetizer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='appetizer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a2c5de5-505d-405e-b7a2-2fcc6830ce07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appetizer</value>
      <webElementGuid>4a36606c-d522-4e24-bc31-f2dc1c7bc7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/category/appetizer'</value>
      <webElementGuid>7cb7ad07-cf90-4d56-83e5-8852bdb3659a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Appetizer
    </value>
      <webElementGuid>263295ef-2ecd-4f21-b2af-c4996ac48237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appetizer&quot;)</value>
      <webElementGuid>7311e130-2661-49e0-b047-8889a33a1b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='appetizer']</value>
      <webElementGuid>47b535b9-87f6-4325-816f-ea2e7ad50d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::button[1]</value>
      <webElementGuid>2b28f4a3-bd76-4649-879f-206b837c0754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main'])[1]/preceding::button[1]</value>
      <webElementGuid>8d6a713a-a6a4-469c-b2ac-e1273719b108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drink'])[1]/preceding::button[2]</value>
      <webElementGuid>32cb2347-27df-41d1-9ec7-d0a515010ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appetizer']/parent::*</value>
      <webElementGuid>b0940110-e6eb-467d-8983-14ffce176aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6698133f-76be-497a-84c3-fe7f3d5a5e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'appetizer' and (text() = '
      Appetizer
    ' or . = '
      Appetizer
    ')]</value>
      <webElementGuid>cc649627-ec44-42a8-b8fa-facba3aaa71e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
