<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Locate (1)</name>
   <tag></tag>
   <elementGuidId>5180b30d-3e14-4693-934f-f8d826f5d3d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='locate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a579ab0-ef29-4e2b-8b9c-bc9db167c0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locate</value>
      <webElementGuid>516f30aa-c8b3-47b3-9cee-e2ab7105c344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>geocodeAddress()</value>
      <webElementGuid>951c6ab7-5a2a-4ad6-93f5-d2e012563127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locate</value>
      <webElementGuid>f070f94c-faa5-4bb4-9e43-caa25a552e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locate&quot;)</value>
      <webElementGuid>e8d0b79e-eb2f-4f8c-96e0-57e7b0a327df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='locate']</value>
      <webElementGuid>8e46ccd1-7205-4db6-909b-fb6afcdd26e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::button[1]</value>
      <webElementGuid>d9aafced-adcc-4934-9e9c-243509366dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>30b40a47-c704-4a69-81de-0e694794a8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'locate', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>995e08db-9091-42af-b703-ba6ce3a11f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Locate']/parent::*</value>
      <webElementGuid>bb779aef-9310-4038-a77e-3a462e8eb5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/button</value>
      <webElementGuid>21e352bd-50e9-49a9-b5c3-c33d0ef41bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'locate' and (text() = 'Locate' or . = 'Locate')]</value>
      <webElementGuid>c07a03c1-4cec-4cb8-a726-304232f502e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
