<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place Order (1)</name>
   <tag></tag>
   <elementGuidId>89b52e45-0663-4435-9781-36c2e20e50ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wg_cary_bill-button > button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;window.location.href='/progress'&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05e5f910-52a1-4207-a8b2-beac7c9c5d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location.href='/progress'</value>
      <webElementGuid>043e621e-0882-4abf-bdb9-1c0f394779c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place Order
    </value>
      <webElementGuid>12dbc1d1-d274-46cb-ba96-53bcb5c82af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wg_cary_bill-button&quot;]/button[1]</value>
      <webElementGuid>96725d83-826c-43a6-978c-7deeb2b1a216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;window.location.href='/progress'&quot;]</value>
      <webElementGuid>6db223b5-a4b5-47fd-ba96-34ce698686d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>7cf4d727-acb5-4af2-a2e2-45928c4c6cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>49484f18-87e4-4943-8232-d68d5538d231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[@class=', '&quot;', 'wg_cary_bill-button', '&quot;', ']/button[1]')])[1]/preceding::button[1]</value>
      <webElementGuid>c5660d46-2804-42db-a765-eae16559e40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place Order']/parent::*</value>
      <webElementGuid>12bbe7c6-0d7a-43ac-9af0-d575f528a5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>fb49b3ed-bdf0-4b17-a8bd-d04fd1be556b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Place Order
    ' or . = 'Place Order
    ')]</value>
      <webElementGuid>790ad1cc-678a-48ee-9753-e91eef90fa4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
