<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appetizer</name>
   <tag></tag>
   <elementGuidId>aa72bd2b-081e-46ab-a220-bf73cfd1f67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appetizer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='appetizer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5b067d7-5fed-4ec4-b02f-829283adf179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appetizer</value>
      <webElementGuid>539438d3-11e5-450c-9ed4-195be4ac5412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/category/appetizer'</value>
      <webElementGuid>9260a5af-5fc0-4a24-9cc1-618385315c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Appetizer
    </value>
      <webElementGuid>c54b2b6d-a7af-4d18-8f05-3ffc85039656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appetizer&quot;)</value>
      <webElementGuid>d32b38d4-0060-4a8e-8cbb-5f61b9b48ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='appetizer']</value>
      <webElementGuid>f3aba76b-ba28-4d82-b911-d30888568e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::button[1]</value>
      <webElementGuid>0b14d410-4502-4397-9ca9-7d73a77851ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main'])[1]/preceding::button[1]</value>
      <webElementGuid>85fbbefb-a946-44dc-abb3-021ddeb09719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drink'])[1]/preceding::button[2]</value>
      <webElementGuid>95ea5f67-6ac7-4e35-824b-e34f51db2b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appetizer']/parent::*</value>
      <webElementGuid>ed1137c2-8a50-4d3e-820c-da6e55a27d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>188dc7f9-3a3c-4a1f-adb0-c655aa06f254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'appetizer' and (text() = '
      Appetizer
    ' or . = '
      Appetizer
    ')]</value>
      <webElementGuid>81666b55-fd2f-44c5-9dab-8f199e0348b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
