<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Locate</name>
   <tag></tag>
   <elementGuidId>fbfe30e0-aab5-42a1-961e-3b711ac98771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='locate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c03bcc69-47db-4820-b263-5100458c5df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locate</value>
      <webElementGuid>3239f107-3ebb-4498-8311-792ea0d8fb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>geocodeAddress()</value>
      <webElementGuid>c30e5803-cbf9-42f2-bca1-8977ca3f8f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locate</value>
      <webElementGuid>394e02d9-64cc-41bf-9d78-27b52751fd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locate&quot;)</value>
      <webElementGuid>94f7d462-6e5f-4ffb-a26f-f2200ffd9b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='locate']</value>
      <webElementGuid>0a28db0b-3fc6-4ccb-bbac-6d7e8cdc6cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::button[1]</value>
      <webElementGuid>cfe1be24-a416-4a79-9308-3b803c060418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>9bdabb72-55f9-4923-a572-0ef140e66e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'locate', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>687f292e-2d69-4049-b639-e58c18637ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Locate']/parent::*</value>
      <webElementGuid>a12fd577-2ba6-48f4-926a-76858fe0ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/button</value>
      <webElementGuid>242a3b42-edb1-4a88-a720-fc453c4869e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'locate' and (text() = 'Locate' or . = 'Locate')]</value>
      <webElementGuid>c7020296-176b-48f6-9f7a-065684e28709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
