<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery Address</name>
   <tag></tag>
   <elementGuidId>4fdaa407-0ec7-4d07-aaa4-f0132b76efde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcb84d3b-11a8-46e9-8214-e26591c4ec81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>866db512-4e26-45e3-9b27-16371731feb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-input</value>
      <webElementGuid>044bdd86-9099-4c20-83d4-d6c1d2058249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-input&quot;)</value>
      <webElementGuid>6c5f97d4-21fb-41c1-bf04-79bf0dcb1b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-input']</value>
      <webElementGuid>f412473c-f841-4bcb-8081-5ce451c93f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>79958044-5401-4bbc-a211-48070bbd9b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-input']</value>
      <webElementGuid>cfd37ebd-c74b-4226-8bf2-6d7f2611a87f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
