<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery Address (1)</name>
   <tag></tag>
   <elementGuidId>30519342-0bee-459c-82a4-d5d4a8d0b794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15f2192d-4760-4f17-a9d1-ac3cdcdc90dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dfab813-985e-4fe6-b107-bc303fc0a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-input</value>
      <webElementGuid>a025b9e6-38ca-4c6f-9f4f-12cf1a294b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-input&quot;)</value>
      <webElementGuid>e034c9fd-135c-4c41-a744-0fdbffd190c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-input']</value>
      <webElementGuid>ed2bcfd1-7d29-44a8-99bb-099f1038d15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>b2445079-f238-4c9a-a32c-d1bc086a92f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address-input']</value>
      <webElementGuid>2cac2029-c70e-4edf-a2f9-008fde67ca4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
