<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order Now (1)</name>
   <tag></tag>
   <elementGuidId>e68ad034-c7f3-4291-90ef-c9b4e312fd9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order-now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ad1e711-3dea-470c-9b07-40d6e3228688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-now</value>
      <webElementGuid>b809f093-022e-4e49-a555-bf1e4ce9c5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/login'</value>
      <webElementGuid>807b9780-ae39-402c-85cb-66c2b1d2ec57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Now</value>
      <webElementGuid>bcd6a29f-30c8-4c13-b109-0e8b328e7af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-now&quot;)</value>
      <webElementGuid>3896a804-cf11-4e03-85a1-ca32fa6aea89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order-now']</value>
      <webElementGuid>5ff6b591-1197-4212-91dd-9fd47d678eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'order-now', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>3472a43d-1be7-45f5-aa83-c4b20d7ddf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order Now']/parent::*</value>
      <webElementGuid>83670ea1-d0a5-4bd8-8330-1af404cedde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dc82b3da-e9ab-4d01-870d-631451499024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'order-now' and (text() = 'Order Now' or . = 'Order Now')]</value>
      <webElementGuid>70fc48ae-35e5-45bc-ac55-2ad3fdcf67b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
